function lengthBytes(length: number): number[] {
  if (length < 128) return [length];
  const bytes: number[] = [];
  for (let value = length; value > 0; value >>= 8) bytes.unshift(value & 0xff);
  return [0x80 | bytes.length, ...bytes];
}

function tagged(tag: number, contents: Uint8Array): Uint8Array {
  return Uint8Array.from([tag, ...lengthBytes(contents.length), ...contents]);
}

function pkcs1ToPkcs8(pkcs1: Uint8Array): Uint8Array {
  const version = Uint8Array.from([0x02, 0x01, 0x00]);
  const rsaAlgorithm = Uint8Array.from([
    0x30, 0x0d,
    0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01,
    0x05, 0x00,
  ]);
  const privateKey = tagged(0x04, pkcs1);
  return tagged(0x30, Uint8Array.from([...version, ...rsaAlgorithm, ...privateKey]));
}

/** Accepts both PKCS#8 and the PKCS#1 PEM generated by GitHub Apps. */
export function githubAppPrivateKeyBytes(pem: string): ArrayBuffer {
  const pkcs1 = pem.includes("-----BEGIN RSA PRIVATE KEY-----");
  const body = pem.replace(/-----BEGIN (?:RSA )?PRIVATE KEY-----|-----END (?:RSA )?PRIVATE KEY-----|\s/g, "");
  const binary = atob(body);
  const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
  const normalized = pkcs1 ? pkcs1ToPkcs8(bytes) : bytes;
  return normalized.buffer as ArrayBuffer;
}
