/**
 * What makes OlivERP installable, in one place.
 *
 * The manifest, the document head, the service worker and the install control
 * in settings all need the same handful of facts — where the application
 * starts, what colour its chrome is, which icons exist. They are declared here
 * so adding an icon or moving the entry point is a single edit rather than
 * four that can drift apart.
 */

import { APP_ROOT } from "@/lib/navigation";

/**
 * Where an installed OlivERP opens.
 *
 * It is the ERP, not the marketing page: someone who has put the application
 * on their home screen has already been convinced. `/` stays inside `scope`
 * anyway, so following a link back to it — or through `/login`, which is where
 * this redirects when there is no session — keeps you in the app window
 * instead of throwing you out to a browser tab.
 */
export const PWA_START_URL = APP_ROOT;

/** The body background of every screen, so there is no flash on launch. */
export const PWA_BACKGROUND_COLOR = "#0f1016";

/**
 * Painted behind the status bar on Android and behind the title bar of an
 * installed desktop window. The same colour as the background: the shell has
 * no coloured header to match.
 */
export const PWA_THEME_COLOR = "#0f1016";

/** Served from `/sw.js` at the root so its default scope is the whole origin. */
export const SERVICE_WORKER_PATH = "/sw.js";

/** Generated by `scripts/generate-icons.mjs` from `public/icon.svg`. */
export const APPLE_TOUCH_ICON = "/icons/apple-touch-icon.png";

export const PWA_ICONS = [
  { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" as const },
  { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" as const },
  // Android crops this one to whatever shape the launcher uses, so it is
  // full-bleed and keeps the mark inside the safe zone.
  { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" as const },
];
