"use client";

import { useState } from "react";

import { ui } from "@/i18n/ui";

const t = (key: string) => ui.en[key] ?? key;
const inputClass = "w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white placeholder-slate-500 transition-all focus:border-primary-500 focus:outline-none";

export type FilterState = { search: string; type: string; channel: string; dateFrom: string; dateTo: string; amountMin: string; amountMax: string };

export default function TransactionFilters({ mode, setMode, channels, filters, onChange, onClear }: { mode: "daily" | "list"; setMode: (mode: "daily" | "list") => void; channels: string[]; filters: FilterState; onChange: (key: keyof FilterState, value: string) => void; onClear: () => void }) {
  const [moreOpen, setMoreOpen] = useState(false);
  const badgeCount = [filters.dateFrom, filters.dateTo, filters.amountMin, filters.amountMax].filter(Boolean).length;
  return (
    <div className="mb-6 flex flex-col gap-3 lg:flex-row lg:items-center lg:gap-4">
      <div className="flex w-fit shrink-0 items-center gap-1 rounded-xl border border-white/10 bg-white/5 p-1">
        <button id="btn-view-daily" type="button" onClick={() => setMode("daily")} className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium transition-all ${mode === "daily" ? "bg-white/10 text-white" : "text-slate-400 hover:text-white"}`} title={t("transactions.viewDaily")}><svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" /></svg><span className="hidden sm:inline">{t("transactions.daily")}</span></button>
        <button id="btn-view-list" type="button" onClick={() => setMode("list")} className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium transition-all ${mode === "list" ? "bg-white/10 text-white" : "text-slate-400 hover:text-white"}`} title={t("transactions.viewList")}><svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1z" clipRule="evenodd" /></svg><span className="hidden sm:inline">{t("transactions.list")}</span></button>
      </div>

      <div id="txn-filters" className={`${mode === "list" ? "flex" : "hidden"} min-w-0 flex-1 flex-col gap-2 sm:flex-row sm:items-center sm:gap-3`}>
        <div className="relative min-w-0 flex-1"><svg xmlns="http://www.w3.org/2000/svg" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clipRule="evenodd" /></svg><input id="filter-search" value={filters.search} onChange={(event) => onChange("search", event.target.value)} type="text" className={`${inputClass} pl-9`} placeholder={t("filters.search")} /></div>
        <select id="filter-type" value={filters.type} onChange={(event) => onChange("type", event.target.value)} className={`${inputClass} shrink-0 sm:w-40`}><option value="">{t("filters.allTypes")}</option><option value="venta">{t("filters.typeVenta")}</option><option value="compra">{t("filters.typeCompra")}</option><option value="ingreso">{t("filters.typeIngreso")}</option><option value="gasto">{t("filters.typeGasto")}</option></select>
        <select id="filter-channel" value={filters.channel} onChange={(event) => onChange("channel", event.target.value)} className={`${inputClass} shrink-0 sm:w-40`}><option value="">{t("filters.allChannels")}</option>{channels.map((channel) => <option key={channel} value={channel}>{channel}</option>)}</select>
        <div className="relative shrink-0"><button id="filters-more-btn" type="button" onClick={() => setMoreOpen((open) => !open)} className="flex w-full items-center justify-center gap-2 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm font-medium text-slate-200 transition-colors hover:bg-white/10 sm:w-auto"><svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-slate-400" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M3 3a1 1 0 011-1h12a1 1 0 011 1v3a1 1 0 01-.293.707L12 11.414V15a1 1 0 01-.293.707l-2 2A1 1 0 018 17v-5.586L3.293 6.707A1 1 0 013 6V3z" clipRule="evenodd" /></svg>{t("filters.more")}{badgeCount > 0 && <span id="filters-badge" className="inline-flex h-[18px] min-w-[18px] items-center justify-center rounded-full bg-primary-500 px-1 text-[10px] font-bold text-white">{badgeCount}</span>}</button><div id="filters-more-panel" className={`${moreOpen ? "block" : "hidden"} absolute right-0 top-full z-50 mt-2 w-72 space-y-4 rounded-xl border border-white/10 bg-[#0f1016] p-4 shadow-xl backdrop-blur-xl`}>
          <div><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">{t("filters.dateRange")}</div><div className="grid grid-cols-2 gap-2"><div><label className="mb-1 block text-[10px] text-slate-500">{t("filters.dateFrom")}</label><input id="filter-date-from" type="date" value={filters.dateFrom} onChange={(event) => onChange("dateFrom", event.target.value)} className={inputClass} /></div><div><label className="mb-1 block text-[10px] text-slate-500">{t("filters.dateTo")}</label><input id="filter-date-to" type="date" value={filters.dateTo} onChange={(event) => onChange("dateTo", event.target.value)} className={inputClass} /></div></div></div>
          <div><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">{t("filters.amountRange")}</div><div className="grid grid-cols-2 gap-2"><div><label className="mb-1 block text-[10px] text-slate-500">{t("filters.amountMin")}</label><input id="filter-amount-min" value={filters.amountMin} onChange={(event) => onChange("amountMin", event.target.value)} type="number" step="0.01" className={inputClass} placeholder="0.00" /></div><div><label className="mb-1 block text-[10px] text-slate-500">{t("filters.amountMax")}</label><input id="filter-amount-max" value={filters.amountMax} onChange={(event) => onChange("amountMax", event.target.value)} type="number" step="0.01" className={inputClass} placeholder="0.00" /></div></div></div>
        </div></div>
        <button id="filter-clear" type="button" onClick={onClear} className="hidden shrink-0 items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium text-slate-400 transition-colors hover:bg-white/5 hover:text-white sm:flex" title={t("filters.clear")}><svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" /></svg><span className="hidden lg:inline">{t("filters.clear")}</span></button>
      </div>
    </div>
  );
}
